config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)' do
    resources :orders
    resources :carts

    resources :products do
    get :who_bought, on: :member
    end

    resources :line_items do
      put 'decrease', on: :member
      put 'increase', on: :member
    end

    get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root 'store#index', as: 'store', via: :all
  end

  get "session/create"
  get "sessions/destroy"

  resources :users

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def decrease(line_item_id)
    current_item = line_items.find(line_item_id)
    if current_item.quantity > 1
      current_item.quantity -= 1
    else
      current_item.destroy
    end
    current_item
  end

  def increase(line_item_id)
    current_item = line_items.find(line_item_id)
    current_item.quantity += 1
    current_item
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  # rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end


  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is currently empty' }
      format.js { }
      format.json { head :no_content }
    end
  end

  private

    # def invalid_cart
    #   logger.error "Attempt to access invalid cart #{params[:id]}"
    #   OrderNotifier.error_occured.deliver
    #   redirect_to store_url, notice: 'Invalid cart'
    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      begin
        @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        logger.error "Attempt to access invalid cart #{params[:id]}"
        OrderNotifier.cart_error_occured(e).deliver   ##### new line
        redirect_to store_url, :notice => 'Invalid cart'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper

  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/views/carts/_cart.html.erb
<h2><%= t('.title') %></h2>

<table>
  <%= render :partial => "line_items/line_item" %>

  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= currency_to_locale(@cart.total_price) %></td>
  </tr>
</table>

<%= button_to t('.empty'), @cart, method: :delete, data: { confirm: 'Are you sure'} %>
<%= button_to t('.checkout'), new_order_path, method: :get, :disabled => @order.present? %>

<!-- which is the same as  -->
<%#= button_to 'Checkout', new_order_path, method: :get, :disabled => !@order.nil? %>




<!-- This is how you would hide the checkout button from a specific page (either by entering the rails_path or the url or its extension in quotes) -->
<%# unless current_page?(new_order_path) || current_page?('/products')%>
  <%#= button_to 'Checkout', new_order_path, method: :get %>
<%# end %>

<!-- no need for these links -->
<%#= link_to 'Edit', edit_cart_path(@cart) %>
<%#= link_to 'Back', carts_path %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
// No need for this since we are no longer using Ajax for emptying cart
// $('#cart').html("<%= j render :partial => 'carts/cart' %>").hide('blind', 50);


// The following are all different code that do as the above separated by two new lines


// $('#cart tr').not('.total_line').remove();
// $('#cart').hide('blind', 50);
//
//
// if ($('#cart').length == 1) { $('#cart').hide("blind", {direction: "vertical" }, 1000)};
//
//
// $('#cart tr').not('.total_line').remove();

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h2>Your Cart</h2>

<table>

  <%= render :partial => "line_items/update_quantity" %>

  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= currency_to_locale(@cart.total_price) %></td>
  </tr>
</table>


<%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure'} %>
<%= button_to "Checkout", new_order_path, method: :get %>


<!-- no need for these links -->
<%#= link_to 'Edit', edit_cart_path(@cart) %>
<%#= link_to 'Back', carts_path %>