config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)' do
    resources :orders
    resources :carts

    resources :products do
    get :who_bought, on: :member
    end

    resources :line_items do
      put 'decrease', on: :member
      put 'increase', on: :member
    end

    get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root 'store#index', as: 'store', via: :all
  end

  get "session/create"
  get "sessions/destroy"

  resources :users

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CartsHelper
  skip_before_action :authorize, only: [:create, :decrease, :increase]
  before_action :set_cart, only: [:create, :decrease, :increase]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_lineitem


  # Activity 4
  # Note that we did not add order_id (or, for that matter, quantity) to the
  # attr_accessible line. This prevents mass assignment of these values by
  # statements such as LineItem.new(params[:line_item]) in
  # app/controllers/line_items_controller.rb. This is a good thing, as it prevents
  # malicious users from creating their own forms that modify an order after
  # it is placed. As product_id is still accessible, it still is theoretically
  # possible for a cracker to substitute a more expensive item for a less
  # expensive item. Close this hole by removing product_id from the accessible list.


  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @line_item }
    end
    rescue ActiveRecord::RecordNotFound
    logger.error "Attempt to access invalid line_item #{ params[ :id ]}"
    redirect_to store_url, :notice => 'Invalid line item'
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def decrease
    #@cart = current_cart
    @line_item = @cart.decrease(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def increase
    #@cart = current_cart
    @line_item = @cart.increase(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])
    # @line_item.quantity = params[:item][:quantity] #added this line here

    respond_to do |format|

      # if @line_item.update_attributes(params[:line_item])


      if @line_item.update(line_item_params)
        if (@line_item.quantity == nil || @line_item.quantity < 1)
          @line_item.destroy
        end
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to(@line_item.cart, notice: 'Line item was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private

    def invalid_lineitem
      logger.error "Attempt to access invalid line item #{params[:id]}"
      redirect_to store_url, notice: 'Invalid line item'
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% @cart.line_items.each do |item| %>
  <% if item == @current_item %>
      <tr id="current_item">
  <% else %>
    <tr>
  <% end %>
      <td><%= item.quantity %>&times;</td>
      <td><%= item.product.title %></td>
      <td class="item_price"><%= currency_to_locale(item.total_price) %></td>
      <td><%= link_to image_tag("plus.jpeg", height: '12', width: '12'), increase_line_item_path(item), :method => :put, remote: true %></td>
      <td><%= link_to image_tag("minus.jpeg", height: '12', width: '12'), decrease_line_item_path(item), :method => :put, remote: true %></td>
<% end %>

<!-- As a result of these two minor changes, the <tr> element of the most recently
changed item in the cart will be tagged with id="current_item". To be used for javascript animation -->

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
            line_item.quantity,
            truncate(line_item.product.title, length: 50)) %>

app/views/line_items/_update_quantity.html.erb
<% @cart.line_items.each do |item| %>
  <%= form_for item do |f|%>
    <tr id="show_cart_table">
      <td>
          <%= f.submit :value => "Update Qty" %>
          <%= f.text_field :quantity, :size => 2 %>
      </td>
      <% end %>

      <td><%= item.product.title %></td>
      <td class="item_price"><%= currency_to_locale(item.total_price) %></td>
      <% if item.quantity == 1 %>
      <td class="item_price"></td>
      <% else  %>
      <td class="item_price">(<%=currency_to_locale(item.product.price)%> each)</td>
      <% end %>
      <td><%= button_to 'Delete Line Item', item, :method => :delete, :confirm => 'Are You Sure' %></td>
  </tr>
<% end %>

app/views/line_items/create.js.erb
$('#notice').hide(); //This is so that you hide any lingering notice once you insert a product in cart via ajax (since page is not being refreshed)

if ($('#cart tr').length == 1) {
  $('#cart').show('blind', 10);
}

$('#cart').html("<%= escape_javascript render :partial => 'carts/cart' %>");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);
// From highlight color to background color by fading

app/views/line_items/decrease.js.erb
$('#cart').html("<%=j render :partial => 'carts/cart'%>");
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);
if ($('#cart tr').length==1) {
    // Hide the cart
    $('#cart').hide('blind', 50);
}

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/increase.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/update.js.erb
$('#show_cart_table').html("<%= escape_javascript render :partial => 'line_items/update_quantity' %>");
// $('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);