config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)' do
    resources :orders
    resources :carts

    resources :products do
    get :who_bought, on: :member
    end

    resources :line_items do
      put 'decrease', on: :member
      put 'increase', on: :member
    end

    get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root 'store#index', as: 'store', via: :all
  end

  get "session/create"
  get "sessions/destroy"

  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>

  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render :partial => "carts/cart" %>
        <% end %>
      <% end %>

      <ul>
        <li> <a href="#"><%= Date.today %></a></li>
        <li> <a href="#"><%= Time.now.to_formatted_s(:time) %></a></li>
        <li><%= link_to t('.home'), store_path %></li>
        <% if @cart %>
        <li><%= link_to t('.mycart'), cart_path(@cart) %></li>
        <% end %>
        <li><%= link_to t('.products'), products_path %></li>
        <li><a href="http://www..../faq"><%=t('.questions')%></a></li>
        <li><a href="http://www..../news"><%=t('.news')%></a></li>
        <li><a href="http://www..../contact"><%=t('.contact')%></a></li>
        <li><a href="http://alexvblog.herokuapp.com" target=_blank>my site</a></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
    </div>

    <div id="main">
      <%= yield %>
    </div>
  </div>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78361051-2', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>


<!--
:db           # => 2008-12-25 14:35:05
:number       # => 20081225143505
:time         # => 14:35
:short        # => 25 Dec 14:35
:long         # => December 25, 2008 14:35
:long_ordinal # => December 25th, 2008 14:35
:rfc822       # => Thu, 25 Dec 2008 14:35:05 +0000
-->